// src/components/YouTubePlayer/YouTubePlayer.svelte
<script>
  import { extractVideoId, isValidUrl } from './YouTubePlayerUtils';
  import './YouTubePlayer.css';

  let {
    videoUrl = '',
    onVideoUrlChange,
    onClose,
    isPlayingAll = false,
  } = $props();

  let videoLink = $state('');
  let player = $state(null);
  let isPlaying = $state(false);
  let playerElement = $state();
  let lastLoadedUrl = $state('');
  let lastPlayAllValue = $state();

  const ensureYouTubeApi = () =>
    new Promise((resolve) => {
      if (window.YT?.Player) {
        resolve(window.YT);
        return;
      }

      const existingScript = document.querySelector('script[src="https://www.youtube.com/iframe_api"]');
      if (!existingScript) {
        const tag = document.createElement('script');
        tag.src = 'https://www.youtube.com/iframe_api';
        document.head.appendChild(tag);
      }

      const previousReady = window.onYouTubeIframeAPIReady;
      window.onYouTubeIframeAPIReady = () => {
        previousReady?.();
        resolve(window.YT);
      };
    });

  const closePlayer = () => {
    if (player) {
      player.destroy();
      player = null;
    }
  };

  const loadPlayer = async (videoId) => {
    if (!playerElement) return;

    await ensureYouTubeApi();
    closePlayer();

    player = new window.YT.Player(playerElement, {
      height: '240',
      width: '426',
      videoId,
      events: {
        onStateChange: (event) => {
          isPlaying = event.data === window.YT.PlayerState.PLAYING;
        },
      },
    });
  };

  const handleEnterClick = () => {
    if (!videoLink || !isValidUrl(videoLink)) return;

    const videoId = extractVideoId(videoLink);
    if (!videoId) return;

    onVideoUrlChange?.(videoLink);
    lastLoadedUrl = videoLink;
    loadPlayer(videoId);
  };

  const handleCloseClick = () => {
    videoLink = '';
    lastLoadedUrl = '';
    onVideoUrlChange?.('');
    isPlaying = false;
    closePlayer();
  };

  const handleRemovePlayer = () => {
    handleCloseClick();
    onClose?.();
  };

  const handleButtonClick = () => {
    player ? handleCloseClick() : handleRemovePlayer();
  };

  const togglePlay = () => {
    if (!player?.pauseVideo || !player?.playVideo) return;

    if (isPlaying) {
      player.pauseVideo();
    } else {
      player.playVideo();
    }
    isPlaying = !isPlaying;
  };

  $effect(() => {
    if (!videoUrl || !isValidUrl(videoUrl) || videoUrl === lastLoadedUrl) return;

    const videoId = extractVideoId(videoUrl);
    if (!videoId) return;

    videoLink = videoUrl;
    lastLoadedUrl = videoUrl;
    loadPlayer(videoId);
  });

  $effect(() => {
    if (lastPlayAllValue === undefined) {
      lastPlayAllValue = isPlayingAll;
      return;
    }

    if (isPlayingAll === lastPlayAllValue) return;

    lastPlayAllValue = isPlayingAll;
    if (isPlayingAll !== isPlaying) {
      togglePlay();
    }
  });

  $effect(() => {
    return () => {
      closePlayer();
    };
  });
</script>

<div class="youtube-player-container">
  <div class="youtube-player-row">
    <input
      type="text"
      bind:value={videoLink}
      placeholder="Enter YouTube link"
      class="youtube-player-input"
    />
    <button onclick={handleEnterClick} class="red-button">View</button>
    <button onclick={handleButtonClick} class="black-button" id="button-close">
      {player ? 'Clear' : 'Close'}
    </button>
  </div>
  <div class:hidden={!player} class="youtube-player-video-wrapper">
    <div bind:this={playerElement}></div>
  </div>
</div>

// src/components/YouTubePlayer/YouTubePlayer.jsx
import React, { useState, useEffect, useRef } from 'react';
import { extractVideoId, isValidUrl } from './YouTubePlayerUtils';
import './YouTubePlayer.css';

const YouTubePlayer = ({ videoUrl, onVideoUrlChange, onClose, isPlayingAll }) => {

    /*
    < --------------- States and References --------------- >
    */

    const [videoLink, setVideoLink] = useState('');
    const [player, setPlayer] = useState(null);
    const [isPlaying, setIsPlaying] = useState(false);

    const playerRef = useRef(null);
    const playerContainerRef = useRef(null);

    /*
    < --------------- Functions: Event Handler --------------- >
    */

    const handleInputChange = (event) => {
        setVideoLink(event.target.value);
    };

    const handleEnterClick = () => {
        if (!videoLink || !isValidUrl(videoLink)) return;
        const videoId = extractVideoId(videoLink);
        onVideoUrlChange(videoLink);
        setVideoUrl(videoLink);
        setVideoLink('');
        loadPlayer(videoId);
    };

    const handleCloseClick = () => {
        setVideoLink('');
        onVideoUrlChange('');
        setIsPlaying(false);
        closePlayer();
    };

    const handleRemovePlayer = () => {
        handleCloseClick();
        onClose();
    };

    const handleButtonClick = () => {
        player ? handleCloseClick() : handleRemovePlayer();
    };

    /*
    < --------------- Functions: YouTube Player --------------- >
    */

    const loadPlayer = (videoId) => {
        setPlayer(
            new window.YT.Player(playerRef.current, {
                height: '240',
                width: '426',
                videoId,
                events: {
                    onStateChange: onPlayerStateChange,
                },
            })
        );
    };

    const closePlayer = () => {
        if (player) {
            player.destroy();
            setPlayer(null);
        }
    };

    const onPlayerStateChange = (event) => {
        setIsPlaying(event.data === window.YT.PlayerState.PLAYING);
    };

    const togglePlay = () => {
        if (!player || !player.pauseVideo || !player.playVideo) return;
        isPlaying ? player.pauseVideo() : player.playVideo();
        setIsPlaying(!isPlaying);
    };

    /*
    < --------------- useEffect Hook --------------- >
    */

    useEffect(() => {
        const tag = document.createElement('script');
        tag.src = 'https://www.youtube.com/iframe_api';
        const firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

        window.onYouTubeIframeAPIReady = () => {
            if (videoUrl && isValidUrl(videoUrl)) {
                const videoId = extractVideoId(videoUrl);
                setVideoLink(videoUrl || '');
                loadPlayer(videoId);
            }
        };
    }, []);

    useEffect(() => {
        if (videoUrl && isValidUrl(videoUrl)) {
            const videoId = extractVideoId(videoUrl);
            setVideoLink(videoUrl || '');
            loadPlayer(videoId);
        }
    }, [videoUrl]);

    useEffect(() => {
        if (isPlayingAll !== isPlaying) {
            togglePlay();
        }
    }, [isPlayingAll]);

    /*
    < --------------- JSX Structure --------------- >
    */

    return (
        <div className="youtube-player-container">
            <div className="youtube-player-row">
                <input
                    type="text"
                    value={videoLink}
                    onChange={handleInputChange}
                    placeholder="Enter YouTube link"
                    className="youtube-player-input"
                />
                <button onClick={handleEnterClick} className="red-button">
                    View
                </button>
                <button onClick={handleButtonClick} className="black-button" id="button-close">
                    {player ? 'Clear' : 'Close'}
                </button>
            </div>
            <div className={`youtube-player-video-wrapper${!player ? ' hidden' : ''}`} ref={playerContainerRef}>
                <div id="player" ref={playerRef}></div>
            </div>
        </div>
    );
};

export default YouTubePlayer;
