// src/components/YouTubeSearch/YouTubeSearch.jsx
import React, { useState, useEffect } from 'react';
import he from 'he';
import './YouTubeSearch.css';
import './SearchResults.css';

const YouTubeSearch = ({ onVideoUrlCopy }) => {

    /*
    < --------------- States and Variable --------------- >
    */

    const [searchTerm, setSearchTerm] = useState('');
    const [searchResults, setSearchResults] = useState([]);

    const [isLoading, setIsLoading] = useState(false);
    const [showResults, setShowResults] = useState(true);

    const [maxResults, setMaxResults] = useState();
    const [maxResultsInput, setMaxResultsInput] = useState('');

    const [copyMode, setCopyMode] = useState(false);
    const [buttonActive, setButtonActive] = useState(false);

    const [previousSearchTerm, setPreviousSearchTerm] = useState('');
    const [previousMaxResults, setPreviousMaxResults] = useState('');

    const maxTitleLength = 60;

    /*
    < --------------- Functions --------------- >
    */

    const handleSearch = async () => {
        try {
            if (searchTerm === previousSearchTerm && maxResults === previousMaxResults) {
                return;
            }

            setSearchResults([]);
            setShowResults(false);

            setIsLoading(true);

            setPreviousSearchTerm(searchTerm);
            setPreviousMaxResults(maxResults);

            const response = await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/search`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ searchTerm, maxResults }),
            });

            if (response.ok) {
                const { items } = await response.json();
                setSearchResults(items);
            } else {
                throw new Error('Search request failed');
            }
        } catch (error) {
            console.error('An error occurred:', error);
        } finally {
            setIsLoading(false);
            setShowResults(true);
        }
    };

    const handleKeyDown = (e) => {
        if (e.key === 'Enter') {
            handleSearch();
        }
    };

    const handleMaxResultsChange = (e) => {
        const input = e.target.value;
        setMaxResultsInput(input);
        setMaxResults(input === '' ? 5 : Math.min(parseInt(input), 10));
    };

    const handleCardClick = async (videoId) => {
        const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
        if (copyMode) {
            try {
                await navigator.clipboard.writeText(videoUrl);
            } catch (error) {
                console.error('Failed to copy the URL to clipboard:', error);
            }
        } else {
            onVideoUrlCopy(videoUrl);
        }
    };

    const handleClearResults = () => {
        setSearchTerm('');
        setSearchResults([]);
        setShowResults(false);
        setPreviousSearchTerm('');
        setPreviousMaxResults('');
    };

    const truncateTitle = (title) => {
        const truncatedTitle = title.length <= maxTitleLength ? title : `${title.substring(0, maxTitleLength)}...`;
        return he.decode(truncatedTitle);
    };

    const toggleCopyMode = () => {
        setCopyMode((prevState) => !prevState);
        setButtonActive((prevState) => !prevState);
    };

    /*
    < --------------- useEffect Hook --------------- >
    */

    useEffect(() => {
        const keepAliveInterval = setInterval(async () => {
            try {
                await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/keep-alive`);
            } catch (error) {
                console.error('An error occurred during keep-alive:', error);
            }
        }, 300000);

        return () => {
            clearInterval(keepAliveInterval);
        };
    }, []);

    /*
    < --------------- JSX Structure --------------- >
    */

    return (
        <div className="container">
            <div className="input-container">
                <input
                    type="text"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    onKeyDown={handleKeyDown}
                    placeholder="Enter search term"
                    className="search-query-input"
                />
                <button onClick={handleSearch} className="red-button">
                    Search
                </button>
                <button
                    onClick={toggleCopyMode}
                    className={`gradient-button ${buttonActive ? 'active' : ''}`}
                >
                    Copy
                </button>
                <button onClick={handleClearResults} className="black-button">
                    Clear
                </button>
                <input
                    type="number"
                    value={maxResultsInput}
                    onChange={handleMaxResultsChange}
                    placeholder="Results (1–10)"
                    className="results-number-input"
                    min="1"
                    max="10"
                />
            </div>

            {isLoading && (
                <div className="search-loading-icon">
                    <div className="search-spinner"></div>
                </div>
            )}

            {showResults && (
                <ul>
                    {searchResults.map((video) => (
                        <li key={video.id.videoId}>
                            <div className="card" onClick={() => handleCardClick(video.id.videoId)}>
                                <img src={video.snippet.thumbnails.default.url} alt="Video Thumbnail" />
                                <h3>{truncateTitle(video.snippet.title)}</h3>
                            </div>
                        </li>
                    ))}
                </ul>
            )}
        </div>
    );
};

export default YouTubeSearch;

// src/components/YouTubeSearch/YouTubeSearch.svelte
<script>
  import he from 'he';
  import './YouTubeSearch.css';
  import './SearchResults.css';

  let { onVideoUrlCopy } = $props();

  let searchTerm = $state('');
  let searchResults = $state([]);
  let isLoading = $state(false);
  let showResults = $state(true);
  let maxResults = $state(undefined);
  let maxResultsInput = $state('');
  let copyMode = $state(false);
  let previousSearchTerm = $state('');
  let previousMaxResults = $state('');

  const maxTitleLength = 60;
  const buttonActive = $derived(copyMode);

  const handleSearch = async () => {
    try {
      if (searchTerm === previousSearchTerm && maxResults === previousMaxResults) {
        return;
      }

      searchResults = [];
      showResults = false;
      isLoading = true;
      previousSearchTerm = searchTerm;
      previousMaxResults = maxResults;

      const response = await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/search`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ searchTerm, maxResults }),
      });

      if (response.ok) {
        const { items } = await response.json();
        searchResults = items;
      } else {
        throw new Error('Search request failed');
      }
    } catch (error) {
      console.error('An error occurred:', error);
    } finally {
      isLoading = false;
      showResults = true;
    }
  };

  const handleKeyDown = (event) => {
    if (event.key === 'Enter') {
      handleSearch();
    }
  };

  const handleMaxResultsChange = (event) => {
    const input = event.target.value;
    const isValidNumber = /^(?:[1-9]|10)$/.test(input);

    if (isValidNumber) {
      maxResultsInput = input;
      maxResults = Number.parseInt(input, 10);
    } else {
      maxResultsInput = '';
      maxResults = undefined;
    }
  };

  const handleCardClick = async (videoId) => {
    const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
    if (copyMode) {
      try {
        await navigator.clipboard.writeText(videoUrl);
      } catch (error) {
        console.error('Failed to copy the URL to clipboard:', error);
      }
    } else {
      onVideoUrlCopy?.(videoUrl);
    }
  };

  const handleClearResults = () => {
    searchTerm = '';
    searchResults = [];
    showResults = false;
    previousSearchTerm = '';
    previousMaxResults = '';
  };

  const truncateTitle = (title) => {
    const truncatedTitle = title.length <= maxTitleLength ? title : `${title.substring(0, maxTitleLength)}...`;
    return he.decode(truncatedTitle);
  };

  $effect(() => {
    const keepAliveInterval = setInterval(async () => {
      try {
        await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/keep-alive`);
      } catch (error) {
        console.error('An error occurred during keep-alive:', error);
      }
    }, 300000);

    return () => {
      clearInterval(keepAliveInterval);
    };
  });
</script>

<div class="container">
  <div class="input-container">
    <input
      type="text"
      bind:value={searchTerm}
      onkeydown={handleKeyDown}
      placeholder="Enter search term"
      class="search-query-input"
    />
    <button onclick={handleSearch} class="red-button">Search</button>
    <button onclick={() => (copyMode = !copyMode)} class:active={buttonActive} class="gradient-button">
      Copy
    </button>
    <button onclick={handleClearResults} class="black-button">Clear</button>
    <input
      type="number"
      value={maxResultsInput}
      oninput={handleMaxResultsChange}
      placeholder="Results (1-10)"
      class="results-number-input"
      min="1"
      max="10"
    />
  </div>

  {#if isLoading}
    <div class="search-loading-icon">
      <div class="search-spinner"></div>
    </div>
  {/if}

  {#if showResults}
    <ul>
      {#each searchResults as video (video.id.videoId)}
        <li>
          <button class="card" onclick={() => handleCardClick(video.id.videoId)}>
            <img src={video.snippet.thumbnails.default.url} alt="Video Thumbnail" />
            <h3>{truncateTitle(video.snippet.title)}</h3>
          </button>
        </li>
      {/each}
    </ul>
  {/if}
</div>
