// src/components/PlayerArray/PlayerArray.jsx
import React, { useState, useEffect } from 'react';
import YouTubePlayer from '../YouTubePlayer/YouTubePlayer';
import './PlayerArray.css';

const PlayerArray = ({ videoUrl }) => {

    /*
    < --------------- State --------------- >
    */

    const [videoUrls, setVideoUrls] = useState(['', '']);
    const [isPlayingAll, setIsPlayingAll] = useState(false);

    /*
    < --------------- Functions --------------- >
    */

    const handleAddPlayer = () => {
        setVideoUrls((prevUrls) => [...prevUrls, '']);
    };

    const handleRemovePlayerAtIndex = (index) => {
        setVideoUrls((prevUrls) => prevUrls.filter((_, i) => i !== index));
    };

    const handleRemoveAllPlayers = () => {
        setVideoUrls([]);
    };

    const handleVideoUrlChange = (index, url) => {
        setVideoUrls((prevUrls) => {
            const updatedUrls = [...prevUrls];
            updatedUrls[index] = url;
            return updatedUrls;
        });
    };

    const togglePlayAll = () => {
        setIsPlayingAll((prevIsPlayingAll) => !prevIsPlayingAll);
    };

    /*
    < --------------- useEffect Hook --------------- >
    */

    useEffect(() => {
        const emptyIndex = videoUrls.findIndex((url) => url === '');
        if (emptyIndex !== -1) {
            setVideoUrls((prevUrls) => {
                const updatedUrls = [...prevUrls];
                updatedUrls[emptyIndex] = videoUrl;
                return updatedUrls;
            });
        }
    }, [videoUrl]);

    /*
    < --------------- JSX Structure --------------- >
    */

    return (
        <div className="player-array-container">
            <div className="player-array-players">
                {videoUrls.map((url, index) => (
                    <div key={`player-${index + 1}`} className="player-array-player">
                        <YouTubePlayer
                            videoUrl={url}
                            onVideoUrlChange={(url) => handleVideoUrlChange(index, url)}
                            onClose={() => handleRemovePlayerAtIndex(index)}
                            isPlayingAll={isPlayingAll}
                        />
                    </div>
                ))}
            </div>
            <div className="player-array-buttons">
                <button id="player-add-button" onClick={handleAddPlayer}>
                    Add YouTube Player
                </button>
                <button id="player-play-pause" onClick={togglePlayAll}>
                    {isPlayingAll ? 'Pause All' : 'Play All'}
                </button>
                <button onClick={handleRemoveAllPlayers}>Remove All Players</button>
            </div>
        </div>
    );
};

export default PlayerArray;

// src/components/PlayerArray/PlayerArray.svelte
<script>
  import YouTubePlayer from '../YouTubePlayer/YouTubePlayer.svelte';
  import './PlayerArray.css';

  let { videoUrl = '' } = $props();
  let videoUrls = $state(['', '']);
  let isPlayingAll = $state(false);
  let previousVideoUrl = $state('');

  const handleAddPlayer = () => {
    videoUrls = [...videoUrls, ''];
  };

  const handleRemovePlayerAtIndex = (index) => {
    videoUrls = videoUrls.filter((_, i) => i !== index);
  };

  const handleRemoveAllPlayers = () => {
    videoUrls = [];
  };

  const handleVideoUrlChange = (index, url) => {
    videoUrls = videoUrls.map((currentUrl, i) => (i === index ? url : currentUrl));
  };

  const togglePlayAll = () => {
    isPlayingAll = !isPlayingAll;
  };

  $effect(() => {
    if (!videoUrl || videoUrl === previousVideoUrl) return;

    const emptyIndex = videoUrls.findIndex((url) => url === '');
    if (emptyIndex !== -1) {
      videoUrls = videoUrls.map((currentUrl, index) => (index === emptyIndex ? videoUrl : currentUrl));
    }

    previousVideoUrl = videoUrl;
  });

  $effect(() => {
    const handleKeyPress = (event) => {
      const isInputElement = event.target instanceof HTMLInputElement;
      if (event.code === 'Space' && !isInputElement) {
        event.preventDefault();
        togglePlayAll();
      }
    };

    window.addEventListener('keydown', handleKeyPress);

    return () => {
      window.removeEventListener('keydown', handleKeyPress);
    };
  });
</script>

<div class="player-array-container">
  <div class="player-array-players">
    {#each videoUrls as url, index (`player-${index + 1}`)}
      <div class="player-array-player">
        <YouTubePlayer
          videoUrl={url}
          onVideoUrlChange={(nextUrl) => handleVideoUrlChange(index, nextUrl)}
          onClose={() => handleRemovePlayerAtIndex(index)}
          {isPlayingAll}
        />
      </div>
    {/each}
  </div>
  <div class="player-array-buttons">
    <button class="red-button" onclick={handleAddPlayer}>Add YouTube Player</button>
    <button class="gradient-button" id="play-pause-button" onclick={togglePlayAll}>
      {isPlayingAll ? 'Pause All' : 'Play All'}
    </button>
    <button onclick={handleRemoveAllPlayers} class="black-button">Remove All Players</button>
  </div>
</div>
